---
- hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: nvim_tag
      prompt: (latest|nightly)
      default: latest
      private: false

    - name: requested_features
      prompt: what features do you want to enable, comma separated list?(all|yml|rust|copilot|python|docker)
      default: "all"
      private: false

  vars:
    neovim_url: "{% if nvim_tag == 'latest' %}https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz{% else %}https://github.com/neovim/neovim/releases/download/{{ nvim_tag }}/nvim-linux64.tar.gz{% endif %}"
    neovim_tarball: "{{ ansible_env.HOME }}/nvim-linux64.tar.gz"
    neovim_extract_path: "{{ ansible_env.HOME }}/nvim-linux64"
    neovim_bin: "{{ neovim_extract_path }}/bin"
    nvim_config: "{{ ansible_env.HOME }}/.config/nvim"

  tasks:
    - set_fact:
        features: '{{ requested_features.split(",") }}'

    - name: Download Neovim tarball
      get_url:
        url: "{{ neovim_url }}"
        dest: "{{ neovim_tarball }}"
        mode: "0644"

    - name: Extract Neovim tarball
      unarchive:
        src: "{{ neovim_tarball }}"
        dest: "{{ ansible_env.HOME }}"
        remote_src: yes

    - name: Delete Neovim tarball
      file:
        path: "{{ neovim_tarball }}"
        state: absent

    - name: Add Neovim to PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH="{{ neovim_bin }}:$PATH"'
        create: yes

    - debug:
        msg: you might need to ```source /home/madiele/.bashrc```

    - name: delete the old LazyVim backup
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "~/.config/nvim.bak"
        - "~/.local/share/nvim.bak"
        - "~/.local/state/nvim.bak"
        #- "~/.cache/nvim.bak"

    - name: make a new backup of current Neovim files
      command: "mv {{ item }} {{ item }}.bak"
      with_items:
        - "~/.config/nvim"
        - "~/.local/share/nvim"
        - "~/.local/state/nvim"
        #- "~/.cache/nvim"

    - name: clone the LazyVim starter
      git:
        repo: "https://github.com/LazyVim/starter"
        dest: "~/.config/nvim"

    - name: remove the .git folder
      file:
        path: "~/.config/nvim/.git"
        state: absent

    - name: enalbe yml lsp
      lineinfile:
        path: "{{ nvim_config }}/lua/config/lazy.lua"
        line: '{ import = "lazyvim.plugins.extras.lang.yaml" },'
        insertafter: '{ "LazyVim/LazyVim", import = "lazyvim.plugins" },'
      when: '"all" in features or "yml" in features'

    - name: enalbe rust lsp
      lineinfile:
        path: "{{ nvim_config }}/lua/config/lazy.lua"
        line: '{ import = "lazyvim.plugins.extras.lang.rust" },'
        insertafter: '{ "LazyVim/LazyVim", import = "lazyvim.plugins" },'
      when: '"all" in features or "rust" in features'

    - name: enalbe python lsp
      lineinfile:
        path: "{{ nvim_config }}/lua/config/lazy.lua"
        line: '{ import = "lazyvim.plugins.extras.lang.python" },'
        insertafter: '{ "LazyVim/LazyVim", import = "lazyvim.plugins" },'
      when: '"all" in features or "python" in features'

    - name: enalbe copilot
      lineinfile:
        path: "{{ nvim_config }}/lua/config/lazy.lua"
        line: '{ import = "lazyvim.plugins.extras.coding.copilot" },'
        insertafter: '{ "LazyVim/LazyVim", import = "lazyvim.plugins" },'
      when: '"all" in features or "copilot" in features'

    - name: enalbe docker lsp
      lineinfile:
        path: "{{ nvim_config }}/lua/config/lazy.lua"
        line: '{ import = "lazyvim.plugins.extras.lang.docker" },'
        insertafter: '{ "LazyVim/LazyVim", import = "lazyvim.plugins" },'
      when: '"all" in features or "docker" in features'

    - name: Check health of Neovim
      command: nvim --headless +checkhealth +q
      timeout: 120
      ignore_errors: true
